// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ildphxmkywgmqiahhnia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsZHBoeG1reXdnbXFpYWhobmlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzg2MzQsImV4cCI6MjA2OTkxNDYzNH0.mhORvgWXsWuomCqsxfkdhiGooaO64FQTGMNeSZcoYSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});